//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMStudent.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificationTable
    {
        public int ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Teacher_ID { get; set; }
        public string Reason { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
    
        public virtual TeacherTable TeacherTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
