//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMStudent.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentsInformationTable
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> User_ID { get; set; }
        public int Profession_ID { get; set; }
        public int Gender_ID { get; set; }
        public int Nationality_ID { get; set; }
        public int Religious_ID { get; set; }
        public int PostOffice_ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Photo { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
    
        public virtual FatherProfesion FatherProfesion { get; set; }
        public virtual GenderTable GenderTable { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual PostOffice PostOffice { get; set; }
        public virtual ReligiousTable ReligiousTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
