//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMStudent.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMStudentContext : DbContext
    {
        public SMStudentContext()
            : base("name=SMStudentContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationForInstallmentTable> ApplicationForInstallmentTables { get; set; }
        public virtual DbSet<ClassRoutinelTable> ClassRoutinelTables { get; set; }
        public virtual DbSet<ClassTable> ClassTables { get; set; }
        public virtual DbSet<DivisionTable> DivisionTables { get; set; }
        public virtual DbSet<EstablishmentFeelTable> EstablishmentFeelTables { get; set; }
        public virtual DbSet<EventTable> EventTables { get; set; }
        public virtual DbSet<ExamFeelTable> ExamFeelTables { get; set; }
        public virtual DbSet<ExamMarksTable> ExamMarksTables { get; set; }
        public virtual DbSet<ExamTable> ExamTables { get; set; }
        public virtual DbSet<ExtraCaricualActiviesTable> ExtraCaricualActiviesTables { get; set; }
        public virtual DbSet<FatherProfesion> FatherProfesions { get; set; }
        public virtual DbSet<GenderTable> GenderTables { get; set; }
        public virtual DbSet<GradeTable> GradeTables { get; set; }
        public virtual DbSet<Kota> Kotas { get; set; }
        public virtual DbSet<meetingFixableTable> meetingFixableTables { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<notificationTable> notificationTables { get; set; }
        public virtual DbSet<ParentsInformationTable> ParentsInformationTables { get; set; }
        public virtual DbSet<PostOffice> PostOffices { get; set; }
        public virtual DbSet<ReligiousTable> ReligiousTables { get; set; }
        public virtual DbSet<SchoolLeavingTable> SchoolLeavingTables { get; set; }
        public virtual DbSet<SessionTable> SessionTables { get; set; }
        public virtual DbSet<StudentAnnualFeeTable> StudentAnnualFeeTables { get; set; }
        public virtual DbSet<StudentAssignmentTable> StudentAssignmentTables { get; set; }
        public virtual DbSet<StudentAttendanceTable> StudentAttendanceTables { get; set; }
        public virtual DbSet<StudentDailyWorklTable> StudentDailyWorklTables { get; set; }
        public virtual DbSet<StudentTable> StudentTables { get; set; }
        public virtual DbSet<StudyTourFeelTable> StudyTourFeelTables { get; set; }
        public virtual DbSet<SubjectTable> SubjectTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeacherAttendanceTable> TeacherAttendanceTables { get; set; }
        public virtual DbSet<TeacherFeedbackTable> TeacherFeedbackTables { get; set; }
        public virtual DbSet<TeacherTable> TeacherTables { get; set; }
        public virtual DbSet<TransportationFeelTable> TransportationFeelTables { get; set; }
        public virtual DbSet<TuisionFeeTable> TuisionFeeTables { get; set; }
        public virtual DbSet<UserAttendanceTable> UserAttendanceTables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<UserTypeTable> UserTypeTables { get; set; }
    }
}
