//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMStudent.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTable()
        {
            this.ApplicationForInstallmentTables = new HashSet<ApplicationForInstallmentTable>();
            this.ClassRoutinelTables = new HashSet<ClassRoutinelTable>();
            this.EstablishmentFeelTables = new HashSet<EstablishmentFeelTable>();
            this.ExamFeelTables = new HashSet<ExamFeelTable>();
            this.ExamMarksTables = new HashSet<ExamMarksTable>();
            this.SchoolLeavingTables = new HashSet<SchoolLeavingTable>();
            this.StudentAnnualFeeTables = new HashSet<StudentAnnualFeeTable>();
            this.StudentAssignmentTables = new HashSet<StudentAssignmentTable>();
            this.StudentAttendanceTables = new HashSet<StudentAttendanceTable>();
            this.StudentDailyWorklTables = new HashSet<StudentDailyWorklTable>();
            this.StudyTourFeelTables = new HashSet<StudyTourFeelTable>();
            this.TeacherFeedbackTables = new HashSet<TeacherFeedbackTable>();
            this.TransportationFeelTables = new HashSet<TransportationFeelTable>();
            this.TuisionFeeTables = new HashSet<TuisionFeeTable>();
        }
    
        public int ID { get; set; }
        public int Session_ID { get; set; }
        public int Division_ID { get; set; }
        public int Class_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public int Kota_ID { get; set; }
        public int Gender_ID { get; set; }
        public int Nationality_ID { get; set; }
        public int FatherProffesion_ID { get; set; }
        public int Religious_ID { get; set; }
        public int PostOffice_ID { get; set; }
        public bool IsActive { get; set; }
        public string Name { get; set; }
        public string RollNumber { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public string CNIC { get; set; }
        public string FNIC { get; set; }
        public string Photo { get; set; }
        public string VaccinationCard_Photo { get; set; }
        public string Birth_Certificate_Photo { get; set; }
        public string Previous_School_Marksheet_Photo { get; set; }
        public string Previous_School_Certificate_Photo { get; set; }
        public string Previous_CGPA { get; set; }
        public string Previous_School_Name { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string FatherPostalAddress { get; set; }
        public string FatherPhone { get; set; }
        public string FatherEmailAddress { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationForInstallmentTable> ApplicationForInstallmentTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassRoutinelTable> ClassRoutinelTables { get; set; }
        public virtual ClassTable ClassTable { get; set; }
        public virtual DivisionTable DivisionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstablishmentFeelTable> EstablishmentFeelTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamFeelTable> ExamFeelTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMarksTable> ExamMarksTables { get; set; }
        public virtual FatherProfesion FatherProfesion { get; set; }
        public virtual GenderTable GenderTable { get; set; }
        public virtual Kota Kota { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual PostOffice PostOffice { get; set; }
        public virtual ReligiousTable ReligiousTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolLeavingTable> SchoolLeavingTables { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAnnualFeeTable> StudentAnnualFeeTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAssignmentTable> StudentAssignmentTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttendanceTable> StudentAttendanceTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentDailyWorklTable> StudentDailyWorklTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyTourFeelTable> StudyTourFeelTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherFeedbackTable> TeacherFeedbackTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportationFeelTable> TransportationFeelTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuisionFeeTable> TuisionFeeTables { get; set; }
    }
}
