//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMStudent.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAttendanceTable
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public System.DateTime AttendDate { get; set; }
        public System.TimeSpan ComingTime { get; set; }
        public System.TimeSpan ClosingTime { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
