//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMStudent.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.ApplicationForInstallmentTables = new HashSet<ApplicationForInstallmentTable>();
            this.ClassRoutinelTables = new HashSet<ClassRoutinelTable>();
            this.ClassTables = new HashSet<ClassTable>();
            this.ClassTables1 = new HashSet<ClassTable>();
            this.DivisionTables = new HashSet<DivisionTable>();
            this.EstablishmentFeelTables = new HashSet<EstablishmentFeelTable>();
            this.EventTables = new HashSet<EventTable>();
            this.ExamFeelTables = new HashSet<ExamFeelTable>();
            this.ExamMarksTables = new HashSet<ExamMarksTable>();
            this.ExamTables = new HashSet<ExamTable>();
            this.ExtraCaricualActiviesTables = new HashSet<ExtraCaricualActiviesTable>();
            this.meetingFixableTables = new HashSet<meetingFixableTable>();
            this.notificationTables = new HashSet<notificationTable>();
            this.ParentsInformationTables = new HashSet<ParentsInformationTable>();
            this.SchoolLeavingTables = new HashSet<SchoolLeavingTable>();
            this.SessionTables = new HashSet<SessionTable>();
            this.StudentAnnualFeeTables = new HashSet<StudentAnnualFeeTable>();
            this.StudentAttendanceTables = new HashSet<StudentAttendanceTable>();
            this.StudentTables = new HashSet<StudentTable>();
            this.StudyTourFeelTables = new HashSet<StudyTourFeelTable>();
            this.SubjectTables = new HashSet<SubjectTable>();
            this.TeacherAttendanceTables = new HashSet<TeacherAttendanceTable>();
            this.TeacherTables = new HashSet<TeacherTable>();
            this.TransportationFeelTables = new HashSet<TransportationFeelTable>();
            this.TuisionFeeTables = new HashSet<TuisionFeeTable>();
            this.UserAttendanceTables = new HashSet<UserAttendanceTable>();
        }
    
        public int ID { get; set; }
        public int UserType_ID { get; set; }
        public int Gender_ID { get; set; }
        public int Nationality_ID { get; set; }
        public int Religious_ID { get; set; }
        public int PostOffice_ID { get; set; }
        public string FullName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public string ContactNO { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationForInstallmentTable> ApplicationForInstallmentTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassRoutinelTable> ClassRoutinelTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassTable> ClassTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassTable> ClassTables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DivisionTable> DivisionTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstablishmentFeelTable> EstablishmentFeelTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTable> EventTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamFeelTable> ExamFeelTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMarksTable> ExamMarksTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamTable> ExamTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraCaricualActiviesTable> ExtraCaricualActiviesTables { get; set; }
        public virtual GenderTable GenderTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meetingFixableTable> meetingFixableTables { get; set; }
        public virtual Nationality Nationality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificationTable> notificationTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParentsInformationTable> ParentsInformationTables { get; set; }
        public virtual PostOffice PostOffice { get; set; }
        public virtual ReligiousTable ReligiousTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolLeavingTable> SchoolLeavingTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionTable> SessionTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAnnualFeeTable> StudentAnnualFeeTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttendanceTable> StudentAttendanceTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTable> StudentTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyTourFeelTable> StudyTourFeelTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectTable> SubjectTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherAttendanceTable> TeacherAttendanceTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherTable> TeacherTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportationFeelTable> TransportationFeelTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuisionFeeTable> TuisionFeeTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAttendanceTable> UserAttendanceTables { get; set; }
        public virtual UserTypeTable UserTypeTable { get; set; }
    }
}
